### ISSUE TITLE
Abstract alignment

### ISSUE THREAD

**Issue by nebula-c** [Isaac-Kwon/ThesisLaTeXPNU#2]
Need \flushleft* (not works for me) or \begin{justify} ... \end{justify}

https://github.com/Isaac-Kwon/ThesisLaTeXPNU/blob/d475a5da4ba58c1271938fcdd657b9941da4b33a/pnuthesis.cls#L504-L574

**Comment by Isaac-Kwon** [comment]
Fixed with commit https://github.com/Isaac-Kwon/ThesisLaTeXPNU/commit/29b215cfde83c7907674dc9d56d8945ae23fe929
